version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-spring
    ports:
      - "8081:8081"
    depends_on:
      - wildfly
    environment:
      - EJB_URL=http://wildfly:8080

  wildfly:
    build:
      context: .
      dockerfile: Dockerfile.ejb
    container_name: ejb-wildfly
    ports:
      - "8080:8080"
      - "9990:9990"